name: develop-branch

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: podverse/podverse_web
        tags: stage
        
    - name: log into stage, deploy latest stage image, then run e2e tests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGE_SSH_HOST }}
        username: ${{ secrets.STAGE_SSH_USERNAME }}
        passphrase: ${{ secrets.STAGE_SSH_PASSPHRASE }}
        key: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
        script: |
          docker stop podverse_web_stage
          docker rm podverse_web_stage
          docker image rm podverse/podverse_web:stage
          docker-compose -f /home/mitch/podverse-ops/docker-compose.stage.yml up -d podverse_web
          sleep 120
          cd podverse-web
          git pull
          npm install
          npm run test:e2e:suite

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
