name: develop-branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
     
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: podverse/podverse_web
        tags: stage
        
    - name: log into stage, deploy latest stage image, then run e2e tests
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          ./podverse-ops/scripts/runLatestPodverseWeb.sh stage
          cd podverse-qa
          git pull
          cd podverse-web
          npm run test:stage
        host: ${{ secrets.STAGE_SSH_HOST }}
        username: ${{ secrets.STAGE_SSH_USERNAME }}
        passphrase: ${{ secrets.STAGE_SSH_PASSPHRASE }}
        privateKey: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
