name: develop-branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read node from package.json
      uses: culshaw/read-package-node-version-actions@v1
      id: package-node-version
    
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: podverse/podverse_web
        tags: |
          latest
          ${{ steps.package-node-version.outputs.version }}
        
    - name: log into stage, deploy latest stage image, then run e2e tests
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          docker stop podverse_web_stage
          docker rm podverse_web_stage
          docker image rm podverse/podverse_web:stage
          docker-compose -f /home/mitch/podverse-ops/docker-compose.prod.yml up -d podverse_web
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USERNAME }}
        passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
        privateKey: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
